"""User modeline embedding alanı eklendi

Revision ID: 2732b01637fe
Revises: 0cddded6efdf
Create Date: 2025-05-16 08:42:05.889330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2732b01637fe'
down_revision = '0cddded6efdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
