"""User modeline is_admin alanı eklendi

Revision ID: 76e8407e9385
Revises: f0a15fb046fe 
Create Date: 2025-05-16 11:12:00.000000 

"""
# Not: Create Date sizin çıktınızda farklı olabilir, bu önemli değil.
# 'Revises' ID'sinin (f0a15fb046fe) bir önceki migrasyonunuzla eşleştiğinden emin olun.

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e8407e9385'
down_revision = 'f0a15fb046fe' # Bu, 'balance' alanını ekleyen migrasyonun ID'si olmalı
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', 
                                      sa.Boolean(), 
                                      nullable=False, 
                                      server_default=sa.text("0"))) # DÜZELTME BURADA (SQLite için False=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
