"""User modeline balance alanı eklendi

Revision ID: f0a15fb046fe
Revises: 2732b01637fe
Create Date: 2025-05-16 09:59:54.275042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a15fb046fe'
down_revision = '2732b01637fe' # Bir önceki revizyon ID'si (embedding alanı ekleyen)
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', 
                                      sa.Numeric(precision=10, scale=2), 
                                      nullable=False, 
                                      server_default=sa.text("'0.00'"))) # DÜZELTME BURADA

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
